- name: Application setup
  ansible.builtin.debug:
    msg: component - {{ role_name }}

- name: User Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Import filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat