- name: Application setup
  ansible.builtin.debug:
    msg: component - {{ role_name }}

- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Copy roboshop Config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Clean old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src:  https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start nginx
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: nginx


- name: Import filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat





