- name: prometheus config
  ansible.builtin.template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{ item }}.yml
    loops:
      - prometheus
      - alerts

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: check for prometheus port 9090
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15