- name: Mongodb schema setup
  when: schema_setup  == "mongo"
  block:
    - name: Copy MongoDB repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.{{ component }}.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js


#  func_print_head "Setup SystemD Service"
#  cp ${script_path}/${component}.service /etc/systemd/system/${component}.service &>>$log_file
#  func_stat_check $?
#
#  func_print_head "Load Schema"
#  mysql -h mysql-dev.gangabhavanikatraparthi.online -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>$log_file
#  sleep 30
#
#  func_stat_check $?
#  fi


- name: Mysql schema setup
  when: schema_setup  == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'dev.{{ component }}.db_host', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'dev.{{ component }}.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'dev.{{ component }}.db_pass', region='us-east-1' ) }} < /app/schema/{{ component }}.sql

