#if [ "${schema_setup}" == "mysql" ]; then
#func_print_head "Install MySQL Client"
#echo "inside mysql"
#echo ${mysql_root_password}
#yum install mysql -y &>>$log_file
#func_stat_check $?
#
#func_print_head "Setup SystemD Service"
#cp ${script_path}/${component}.service /etc/systemd/system/${component}.service &>>$log_file
#func_stat_check $?
#
#func_print_head "Load Schema"
#mysql -h mysql-dev.gangabhavanikatraparthi.online -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>$log_file
#sleep 30
#
#func_stat_check $?
#fi

- name: Mongodb setup
  blocks:
    - name: Copy MongoDB repo
      ansible.builtin.copy:
        src: /mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }} </app/schema/${{ component }}.js
  when: schema_setup  == "mongo"
